name: Hallo-Welt-Aktion

on:
  workflow_dispatch:

env: 
  DEVOPS_DIR: .devops

jobs:
  hallo_welt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout des Repository
        uses: actions/checkout@v4

      - name: Ausführung des Skripts
        run: python ${{ env.DEVOPS_DIR }}/hello_welt.py
        shell: shy